[package]
name = "one"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "one"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.2"
